version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: metrics
      POSTGRES_PASSWORD: metrics
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
  spark:
    image: bitnami/spark:3.5
    environment:
      SPARK_MODE: master
